In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Date': pd.date_range('2023-02-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 
               'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 
               'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 
            'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 
            'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep     Month Quarter
0  2023-02-01       A   East    356     36   John  February      Q1
1  2023-02-02       B   West    345     61   Mary  February      Q1
2  2023-02-03       C  North    378     47    Bob  February      Q1
3  2023-02-04       D  South    489     25  Alice  February      Q1
4  2023-02-05       A   East    436     93   John  February      Q1
5  2023-02-06       B   West    872     19   Mary  February      Q1
6  2023-02-07       C  North    922     95    Bob  February      Q1
7  2023-02-08       D  South    165     56  Alice  February      Q1
8  2023-02-09       A   East    537     88   John  February      Q1
9  2023-02-10       B   West    833     40   Mary  February      Q1
10 2023-02-11       C  North    681     98    Bob  February      Q1
11 2023-02-12       D  South    988     57  Alice  February      Q1
12 2023-02-13       A   East    978     70   John  February      Q1
13 2023-02-14       B   West    861     28   Mary  February      Q1
14 2023-02-15       C  North    518     85    Bob  February      Q1
15 2023-02-16       D  South    353     74  Alice  February      Q1
16 2023-02-17       A   East    722     70   John  February      Q1
17 2023-02-18       B   West    435     61   Mary  February      Q1
18 2023-02-19       C  North    314     89    Bob  February      Q1
19 2023-02-20       D  South    906     97  Alice  February      Q1

In [5]:
# cross tabs
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     537.0    NaN    NaN    NaN
North      NaN    NaN  518.0    NaN
South      NaN    NaN    NaN  489.0
West       NaN  833.0    NaN    NaN

In [12]:
pivot2= pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     380.4    NaN    NaN    NaN  54.4   NaN   NaN   NaN
North      NaN    NaN  655.6    NaN   NaN   NaN  64.0   NaN
South      NaN    NaN    NaN  606.8   NaN   NaN   NaN  46.6
West       NaN  546.0    NaN    NaN   NaN  42.4   NaN   NaN