In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:

X = df.drop('species', axis=1)
y = df['species']

In [4]:

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [5]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y_encoded)

In [6]:

from sklearn.neighbors import KNeighborsClassifier

In [7]:

model_knn= KNeighborsClassifier(n_neighbors=13)
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [8]:

model_knn.score(X_test,y_test)

0.9666666666666667

In [9]:
from sklearn.svm import SVC
model_svm= SVC( gamma='auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [10]:
model_svm.score(X_test,y_test)

0.9666666666666667

In [11]:
# now lets use grid search cv
from sklearn.model_selection import GridSearchCV

In [12]:
classifier= GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score =False)

In [13]:
# if we use gridsearch then we have not to use train test split elsewhere it done internally so normal data can we okay
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [14]:
classifier.cv_results_

{'mean_fit_time': array([0.00202103, 0.00333724, 0.00279727, 0.00241952, 0.00260382,
        0.00340619, 0.00224671, 0.00171628]),
 'std_fit_time': array([3.78974244e-04, 8.59728518e-04, 2.49536297e-04, 6.87574381e-05,
        1.36707425e-04, 3.74436287e-04, 2.56678151e-04, 3.82435886e-05]),
 'mean_score_time': array([0.00151072, 0.00259147, 0.00242753, 0.00261998, 0.00215826,
        0.00273204, 0.00174861, 0.00130844]),
 'std_score_time': array([1.01122266e-04, 7.29678441e-04, 4.72409034e-04, 1.31249111e-03,
        7.14550624e-05, 4.03456932e-04, 2.01287554e-04, 7.67100432e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [15]:
result = pd.DataFrame(classifier.cv_results_)
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002021,0.000379,0.001511,0.000101,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003337,0.000860,0.002591,0.000730,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002797,0.000250,0.002428,0.000472,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002420,0.000069,0.002620,0.001312,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002604,0.000137,0.002158,0.000071,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5

In [16]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [17]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(SVC(gamma='auto'),
    {
        'C': [1, 10, 20, 30],
        'kernel': ['rbf', 'linear']
    },
    cv=5,
    n_iter=8,
    random_state=42
)

random_search.fit(X, y)
random_search.best_params_

{'kernel': 'rbf', 'C': 1}